# Code Book

This contains all of the data fields in the `tidySet.txt` file.

## Identifiers

 - `subject` - `integer` - The ID of the test subject
   - 1 - 30
 - `activity` - `string` - The type of activity that they were performing when the measurements were taken
   - Walking
   - Walking Upstairs
   - Walking Downstairs
   - Sitting
   - Standing
   - Laying

## Measurements

These variables are all of the `mean` values for the corresponding measurement based on the subject and the activity, all numeric type.
"timeBodyaccelerometermeanX"                     
"timeBodyaccelerometermeanY"                     
"timeBodyaccelerometermeanZ"                     
"timeBodyaccelerometerstdX"                      
"timeBodyaccelerometerstdY"                      
"timeBodyaccelerometerstdZ"                      
"timeGravityaccelerometermeanX"                  
"timeGravityaccelerometermeanY"                  
"timeGravityaccelerometermeanZ"                  
"timeGravityaccelerometerstdX"                   
"timeGravityaccelerometerstdY"                   
"timeGravityaccelerometerstdZ"                   
"timeBodyaccelerometerJerkmeanX"                 
"timeBodyaccelerometerJerkmeanY"                 
"timeBodyaccelerometerJerkmeanZ"                 
"timeBodyaccelerometerJerkstdX"                  
"timeBodyaccelerometerJerkstdY"                  
"timeBodyaccelerometerJerkstdZ"                  
"timeBodygyroscopemeanX"                         
"timeBodygyroscopemeanY"                         
"timeBodygyroscopemeanZ"                         
"timeBodygyroscopestdX"                          
"timeBodygyroscopestdY"                          
"timeBodygyroscopestdZ"                          
"timeBodygyroscopeJerkmeanX"                     
"timeBodygyroscopeJerkmeanY"                     
"timeBodygyroscopeJerkmeanZ"                     
"timeBodygyroscopeJerkstdX"                      
"timeBodygyroscopeJerkstdY"                      
"timeBodygyroscopeJerkstdZ"                      
"timeBodyaccelerometermagnitudemean"             
"timeBodyaccelerometermagnitudestd"              
"timeGravityaccelerometermagnitudemean"          
"timeGravityaccelerometermagnitudestd"           
"timeBodyaccelerometerJerkmagnitudemean"         
"timeBodyaccelerometerJerkmagnitudestd"          
"timeBodygyroscopemagnitudemean"                 
"timeBodygyroscopemagnitudestd"                  
"timeBodygyroscopeJerkmagnitudemean"             
"timeBodygyroscopeJerkmagnitudestd"              
"frequencyBodyaccelerometermeanX"                
"frequencyBodyaccelerometermeanY"                
"frequencyBodyaccelerometermeanZ"                
"frequencyBodyaccelerometerstdX"                 
"frequencyBodyaccelerometerstdY"                 
"frequencyBodyaccelerometerstdZ"                 
"frequencyBodyaccelerometermeanFreqX"            
"frequencyBodyaccelerometermeanFreqY"            
"frequencyBodyaccelerometermeanFreqZ"            
"frequencyBodyaccelerometerJerkmeanX"            
"frequencyBodyaccelerometerJerkmeanY"            
"frequencyBodyaccelerometerJerkmeanZ"            
"frequencyBodyaccelerometerJerkstdX"             
"frequencyBodyaccelerometerJerkstdY"             
"frequencyBodyaccelerometerJerkstdZ"             
"frequencyBodyaccelerometerJerkmeanFreqX"        
"frequencyBodyaccelerometerJerkmeanFreqY"        
"frequencyBodyaccelerometerJerkmeanFreqZ"        
"frequencyBodygyroscopemeanX"                    
"frequencyBodygyroscopemeanY"                    
"frequencyBodygyroscopemeanZ"                    
"frequencyBodygyroscopestdX"                     
"frequencyBodygyroscopestdY"                     
"frequencyBodygyroscopestdZ"                     
"frequencyBodygyroscopemeanFreqX"                
"frequencyBodygyroscopemeanFreqY"                
"frequencyBodygyroscopemeanFreqZ"                
"frequencyBodyaccelerometermagnitudemean"        
"frequencyBodyaccelerometermagnitudestd"         
"frequencyBodyaccelerometermagnitudemeanFreq"    
"frequencybodyaccelerometerJerkmagnitudemean"    
"frequencybodyaccelerometerJerkmagnitudestd"     
"frequencybodyaccelerometerJerkmagnitudemeanFreq"
"frequencybodygyroscopemagnitudemean"            
"frequencybodygyroscopemagnitudestd"             
"frequencybodygyroscopemagnitudemeanFreq"        
"frequencybodygyroscopeJerkmagnitudemean"        
"frequencybodygyroscopeJerkmagnitudestd"         
"frequencybodygyroscopeJerkmagnitudemeanFreq"    
"angletimebodyaccelerometerMeangravity"          
"angletimebodyaccelerometerJerkMeangravityMean"  
"angletimebodygyroscopeMeangravityMean"          
"angletimebodygyroscopeJerkMeangravityMean"      
"angleXgravityMean"                              
"angleYgravityMean"                              
"angleZgravityMean"
